//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOOBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDataWithoutIDs
    {
        public string AnimalName { get; set; }
        public string AnimalSpecies { get; set; }
        public int AnimalAge { get; set; }
        public decimal AnimalPrice { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public int OrderQuantity { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
